# If this version is updated, ensure that the `requirements.txt` python version is updated, as well as your local
# python version
FROM freqtradeorg/freqtrade:2021.5

# Switch user to root if you must install something from apt. Don't forget to switch the user back below!
#USER root

RUN pip install --user tqdm

#USER ftuser
