---
version: '3'
services:
  freqtrade:
    build:
      # context has to be the root of the repo so the Dockerfile can copy the source directory
      context: ../../
      dockerfile: "./src/freqtrade/Dockerfile"
    restart: unless-stopped
    container_name: freqtrade

    # Used for debugging the image
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t
#    entrypoint: "/bin/bash"

    # The directory structure of the container mounts replicates that of the repo's. This is to ensure python modules
    # will work inside and out of the container
    volumes:
      - "../:/capia/src"

    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    ports:
      - "8080:8080"

    # Environment variables from root of the repo
    env_file:
      - "../../.env"

    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /capia/src/freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////capia/src/freqtrade/user_data/tradesv3.sqlite
      --config /capia/src/freqtrade/user_data/config.json
      --strategy DeepProbabilisticStrategy
